# Generated by Django 4.1.1 on 2022-11-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterOnTreeApp', '0003_alter_letter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='title',
        ),
        migrations.AlterField(
            model_name='letter',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
